C:\VulkanSDK\1.4.341.1\Bin\glslc.exe vert.vert -o vert.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe diffuse.frag -o diffuse.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe pbr.frag -o pbr.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe fullScreen_v.vert -o fullScreen_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe lighting_f.frag -o lighting_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe lighting_rtx.frag -o lighting_rtx.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe ssao_f.frag -o ssao_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe blur_f.frag -o blur_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe denoising_f.frag -o denoising_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe taa_f.frag -o taa_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe fxaa_f.frag -o fxaa_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition_v.vert -o composition_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition_f.frag -o composition_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe chromaticAberration_f.frag -o chromaticAberration_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe toneMapping_f.frag -o toneMapping_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe bloom_f.frag -o bloom_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe colorAddition_f.frag -o colorAddition_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe shadows.geom -o shadows.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe shadows_f.frag -o shadows_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe motionVectors_f.frag -o motionVectors_f.spv